AWSTemplateFormatVersion: '2010-09-09'
Description: Template to deploy ECS cluster with ec2 Type workers

Parameters:
  AutoScalingDesiredCapacity:
    Type: Number
    Default: 2
  AutoScalingGroupName:
    Type: String
    Default: ''
  AutoScalingMaxSize:
    Type: Number
    Default: 100
  AutoScalingMinSize:
    Type: Number
    Default: 1
  EcsClusterName:
    Type: String
    Default: ''
    Description: Ecs Cluster Name
  ImageId:
    Type: String
    Default: ami-0c09d65d2051ada93
    Description: Ec2 ImageId
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Ec2 Instance Type
  KeyName:
    Type: String
    Default: ''
    Description: Ec2 key name
  LaunchConfigurationName:
    Type: String
    Default: ''
  LoadBalancerName:
    Type: String
    Default: ''
  TargetGroupArnName:
    Type: String
    Default: ''
  TargetGroupName:
    Type: String
    Default: ''
  VolumeSize:
    Type: String
    Default: 30
    Description: Ec2 Ebs VolumeSize
  VpcId:
    Type: String
    Default: ''
    Description: VpcId of Ec2 instance
  VpcCird:
    Type: String
    Default: ''
  VpcSubnets:
    Type: List<String>
    Default: ''
  UserName:
    Type: String
    Default: ''
    Description: Name of the user
  
Resources:
  AlbScaleUpAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: True
      AlarmActions:
        - !Ref Ec2AutoScalingUpPolicy
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroupName
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 60
      Statistic: Average
      Threshold: 80

  AlbScaleDownAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: True
      AlarmActions:
        - !Ref Ec2AutoScalingDownPolicy
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroupName
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 60
      Statistic: Average
      Threshold: 50

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref AlbTargetGroup
          Type: forward
      LoadBalancerArn: !Ref EcsLoadBalancer
      Port: 80
      Protocol: HTTP

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: 'ALB security group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
      Tags:
        -
          Key: username
          Value: !Ref UserName

  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupName
      Port: 80
      Protocol: HTTP
      Tags: 
        -
          Key: username
          Value: !Ref UserName
      VpcId: !Ref VpcId

  AutoScalingLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize
      IamInstanceProfile: !Ref Ec2Profile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      LaunchConfigurationName: !Ref LaunchConfigurationName
      SecurityGroups: [ !Ref Ec2SecurityGroup ]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo 'ECS_CLUSTER=${EcsCluster}' >> /etc/ecs/ecs.config
      
  Ec2AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroupName
      DesiredCapacity: !Ref AutoScalingDesiredCapacity
      LaunchConfigurationName: !Ref AutoScalingLaunchConfig
      MaxSize: !Ref AutoScalingMaxSize
      MinSize: !Ref AutoScalingMinSize
      MetricsCollection:
        - Granularity: 1Minute
      Tags:
        - Key: username
          PropagateAtLaunch: True
          Value: !Ref UserName
      TargetGroupARNs: [ !Ref AlbTargetGroup ]
      VPCZoneIdentifier: !Ref VpcSubnets

  Ec2AutoScalingUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref Ec2AutoScalingGroup
      ScalingAdjustment: 2

  Ec2AutoScalingDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref Ec2AutoScalingGroup
      ScalingAdjustment: -2

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref EcsClusterName
      Tags:
        -
          Key: username
          Value: !Ref UserName
      
  EcsEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref Ec2Profile
      KeyName: !Ref KeyName
      Tags:
        -
          Key: username
          Value: !Ref UserName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo 'ECS_CLUSTER=${EcsCluster}' >> /etc/ecs/ecs.config
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize
      SecurityGroupIds: [ !Ref Ec2SecurityGroup ]

  Ec2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ ecsInstanceRole ]

  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: 'ecs ec2 group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '1'
          ToPort: '65535'
          CidrIp: !Ref VpcCird
      Tags:
        -
          Key: username
          Value: !Ref UserName
        
  EcsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      SecurityGroups: [ !Ref AlbSecurityGroup ]
      Subnets: !Ref VpcSubnets
      Tags:
        -
          Key: username
          Value: !Ref UserName

Outputs:
  LoadBalancerDns:
    Description: The Dns Address of LoadBalancer
    Value: !GetAtt EcsLoadBalancer.DNSName
  TargetGroupArn:
    Value: !Ref AlbTargetGroup
    Description: Arn of load balancer target group
    Export:
      Name: !Ref TargetGroupArnName