AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create ecs task

Parameters:
  ContainerCpu:
    Type: Number
    Default: 256
  ContainerImage:
    Type: String
    Default: nginx:latest
    Description: Image name of docker container
  ContainerMemoryReservation:
    Type: Number
    Default: 300
  ContainerName:
    Type: String
    Default: nginx
    Description: Name of docker container
  DesiredCount:
    Type: Number
    Default: 1
  EcsClusterName:
    Type: String
    Default: ''
  LaunchType:
    Type: String
    Default: EC2
    AllowedValues: [ EC2, FARGATE ]
  SchedulingStrategy:
    Type: String
    Default: REPLICA
    AllowedValues: [ REPLICA, DAEMON ]
  TaskName:
    Type: String
    Default: nginx_server
    Description: Name/Family of the task

Resources:
  EcsTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx_server
      ContainerDefinitions:
        -
          Name: !Ref ContainerName
          Image: !Ref ContainerImage
          Cpu: !Ref ContainerCpu
          MemoryReservation: !Ref ContainerMemoryReservation
          PortMappings:
            -
              Protocol: 'tcp'
              ContainerPort: 80
              HostPort: 0
  
  EcsTaskService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsClusterName
      DesiredCount: !Ref DesiredCount
      LaunchType: !Ref LaunchType
      PlacementStrategies:
        - Type: spread
          Field: host
      TaskDefinition: !Ref EcsTask
      SchedulingStrategy: !Ref SchedulingStrategy
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50