AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create ecs task

Parameters:
  ContainerCpu:
    Type: Number
    Default: 256
  ContainerImage:
    Type: String
    Default: nginx:latest
    Description: Image name of docker container
  ContainerMemoryReservation:
    Type: Number
    Default: 300
  ContainerName:
    Type: String
    Default: nginx
    Description: Name of docker container
  ContainerPort:
    Type: Number
    Default: 80
    Description: Port of docker container to expose
  DesiredCount:
    Type: Number
    Default: 1
  EcsClusterName:
    Type: String
    Default: ''
  LaunchType:
    Type: String
    Default: EC2
    AllowedValues: [ EC2, FARGATE ]
  LoadBalancerName:
    Type: String
    Default: ''
  SchedulingStrategy:
    Type: String
    Default: REPLICA
    AllowedValues: [ REPLICA, DAEMON ]
  ServiceName:
    Type: String
    Default: ''
    Description: Name of the ecs service
  TargetGroupArnName:
    Type: String
    Default: ''
  TaskName:
    Type: String
    Default: nginx_server
    Description: Name/Family of the task

Resources:
  EcsTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskName
      ContainerDefinitions:
        -
          Name: !Ref ContainerName
          Image: !Ref ContainerImage
          Cpu: !Ref ContainerCpu
          MemoryReservation: !Ref ContainerMemoryReservation
          PortMappings:
            -
              Protocol: 'tcp'
              ContainerPort: !Ref ContainerPort
              HostPort: 0
  
  EcsTaskService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsClusterName
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: !Ref DesiredCount
      LaunchType: !Ref LaunchType
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort:  !Ref ContainerPort
          TargetGroupArn:
            Fn::ImportValue: !Ref TargetGroupArnName
      PlacementStrategies:
        - Type: spread
          Field: host
      SchedulingStrategy: !Ref SchedulingStrategy
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref EcsTask
